export const chats = [
  {
    id: '1',
    title: 'Salome',
    message: 'You reacted 👍 to "Guys we should hangout on satusrday"',
    time: 'Yesterday',
    isPinned: true,
    avatar: require('@/assets/images/salome.png'),
    numberOfMessage: 2,
    isUnRead: true,
    category: 'Unread',
  },
  {
    id: '2',
    title: 'Computer Vision and Cybersecurity',
    message: 'You reacted 👍 to "NO Java this week"',
    time: 'Yesterday',
    avatar: null,
    isPinned: true,
    numberOfMessage: 45,
    isUnRead: true,
    category: 'Groups',
  },
  {
    id: '3',
    title: 'MEng Artificial Intelligence and Computing',
    message: 'You: You deleted this message',
    time: '1/29/25',
    avatar: null,
    category: 'Lead',
  },
  {
    id: '4',
    title: 'Dummy - Talk to myself 🤔',
    message: '✓ You: 👌 LEARN LARAVEL THE EAS...',
    time: 'Yesterday',
    avatar: require('@/assets/images/suzy.png'),
    category: 'Family',
  },
  {
    id: '5',
    title: 'Cyril',
    message: 'what about the creator db?',
    time: '9:51 AM',
    avatar: require('@/assets/images/cyril.png'),
    isDraft: false,
    numberOfMessage: 5,
    isUnRead: true,
    isMuted: true,
    category: 'Family',
  },
  {
    id: '6',
    title: 'RBC - Made in Cameroon 🇨🇲',
    message: 'Draft: Bbb',
    time: '9:51 AM',
    avatar: require('@/assets/images/girl.jpeg'),
    numberOfMessage: 45,
    isUnRead: true,
    category: 'Lead',
  },
];
